add_newline = false

format = """
$os\
$username\
$directory\
$git_branch\
$git_status\
$nodejs\
$python\
$rust
$character
"""

[os]
disabled = false
format = "[$symbol]($style)"
symbols = { Macos = " ", Linux = " ", Windows = " " }
style = "fg:#00afff"   

[username]
show_always = true
#style_user = "fg:#00afff"
format = "[\\[$user\\]]($style)"
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"

[directory]
style = "fg:#ffd75f"   
format = "   [$path]($style)"
truncation_length = 7
home_symbol=""

[git_branch]
symbol = ""
style = "fg:#5fff87"   
format = " [$symbol $branch]($style)"

[git_status]
style = "fg:#ff5f5f"    
format = "[$all_status$ahead_behind ]($style)"

[nodejs]
symbol = ""
style = "fg:#afff00"   
format = " [$symbol $version]($style)"

[python]
symbol = ""
style = "fg:#ffaf00"   
format = " [$symbol $version]($style)"

[rust]
symbol = ""
style = "fg:#ff5f87"   
format = " [$symbol $version]($style)"

[character]
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = " [➜](bold fg:#ff0000)"
